/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/mavi.gltf -o src/components/mavi.jsx -r public 
*/

import React, { useRef } from 'react'
import { SpotLight, useGLTF } from '@react-three/drei'
import { PointLight } from 'three'

export function Mavi(props) {
  const { nodes, materials } = useGLTF('../models/mavi.gltf')
  const roughness = materials['Material.001'].roughness = 0.75;
  const metalness = materials['Material.001'].metalness = 0.1;
  
  return (
    <group {...props} dispose={null}>
     
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']}
       roughness={roughness} metalness={metalness}/>
    </group>
  )
}

useGLTF.preload('/models/mavi.gltf')
