/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/pembe.gltf -o src/components/pembe.jsx -r public 
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Pembe(props) {
  const { nodes, materials } = useGLTF('/models/pembe.gltf')
  const [hovered, setHovered] = useState(false)
  const meshRef = useRef()

  useFrame(() => {
    if (hovered) {
      meshRef.current.rotation.x += 0.01;
      meshRef.current.rotation.y += 0.01;
    }
  })

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} 
      material={materials['Material.001']}
      onPointerOver={(e) => setHovered(true)}  
      onPointerOut={(e) => setHovered(false)}/>
    </group>
  )
}

useGLTF.preload('/models/pembe.gltf')
